### ISSUE TITLE
display live data in chart

### ISSUE THREAD

**Issue by bastifix** [yannbf/ionic2-components#1]
Hi, with ionic 1 it was easy to bind the chart-data to a variable and the chart always adapted live to the actual values
`chart-data="graph.data"`
Do you know how to do this now with ionic 2?
With
`data: this.graph.data`
the chart loads with the right data, but I have to recall the chart-function to update the chart with the new data completely.
Thanks!

**Comment by yannbf** [comment]
Hey @wurstel, I'm no one to say that, but I believe that when you create a chart, therefore create a new instance like `new Chart(..)`, the data is **copied** into this new instance. Whenever you make some live changes, that data variable that you passed has nothing to do with the chart anymore.

What you can do, which is quite easy though, is reset the specific data you want to change by using `this.yourChart.data` and call `this.yourChart.update()` after that.

I just pushed an example for you to check out.

**Comment by bastifix** [comment]
Thanks! Works perfect for my needs ;-)

**Comment by yannbf** [comment]
Great. Glad to know this repo was of help for you!
