### ISSUE TITLE
Remove google maps 

### ISSUE THREAD

**Issue by Finn-the-programmer** [yannbf/ionic2-components#103]
I build a simple application which dont need maps 

When i try to add platform ios
It takes tooo much time to download google maps plugin

And if i download google maps  manually it show an error

So please, i dont need google maps and it takes time from me more than develeopment time.

How to build my application without need to go through google map stuff.

**Comment by Finn-the-programmer** [comment]
@yannbf any help please

**Comment by pwqw** [comment]
I think it's more a question for [stackoverflow](http://stackoverflow.com/) or [ionic forum](http://forum.ionicframework.com/) than a repository issue.

But, you can try removing the plugin:
``` bash
ionic cordova plugin remove cordova-plugin-googlemaps
``` 
also if you do not need it:
``` bash
ionic cordova plugin remove cordova-plugin-geolocation
```

**Comment by yannbf** [comment]
Indeed it's what @AlexisCaffa mentioned, this repository contains multiple examples of functionality, the main intention is that you can try it out and extract whatever is useful for you to your own project 👍
