### ISSUE TITLE
"export 'DOCUMENT' was not found in '@angular/platform-browser'

### ISSUE THREAD

**Issue by iqasim-com** [yannbf/ionic2-components#111]
**I'm submitting a ...**  (check one with "x")

[x] bug report
[ ] feature request
[ ] support request

**Steps to reproduce the bug:**
Hi everyone,
I am using ionic with Angular 8, i have just installed ionic-angular dependency for ion-slider. I want to add navigation arrows on ion-slider for navigation but getting the below error

**Related code:**
```
   "dependencies": {
    "@angular/animations": "^8.2.8",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "^8.2.13",
    "@angular/core": "^8.2.13",
    "@angular/forms": "^8.2.13",
    "@angular/platform-browser": "^8.2.13",
    "@angular/platform-browser-dynamic": "^8.2.13",
    "@angular/router": "^8.2.13",
    "@busacca/ng-pick-datetime": "^8.1.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "ionic-angular": "3.9.2",
    "angular-highcharts": "^8.0.3",
    "angularx-qrcode-cil": "^1.0.2",
    "core-js": "^2.5.4",
    "highcharts": "^7.2.1",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.3",
    "simple-keyboard": "^2.26.20",
    "sweetalert2": "^9.3.1",
    "tslib": "^1.9.0",
    "typescript": "^3.5.3",
    "zone.js": "^0.9.1"
  },```

**Important information:**
<!-- State important information if needed, such as OS version, hardware info, ionic info, etc. -->
![image](https://user-images.githubusercontent.com/23281307/77255874-68576280-6c8c-11ea-8998-4f81ec971c1c.png)

**Comment by yannbf** [comment]
Hey @mqasim1990, thanks for opening an issue. The problem you are having might be related to lack of compatibility. This repo is a bit outdated, it focuses on Ionic 3, which supports angular 4/5.
As you're using Angular 8, I'd suggest you to follow Ionic 5's documentation, which do support angular 8. You should not use both ionic-angular and @ionic/angular in the same project. Please follow the official documentation on setting up your project at https://ionicframework.com/docs/angular/your-first-app

And here is the link for the docs on the slides component:
https://ionicframework.com/docs/api/slides#usage

I'll be closing this issue as it does not apply to this repo. Hope that helps you!
