### ISSUE TITLE
Petition: Styled sidemenu

### ISSUE THREAD

**Issue by Fdom92** [yannbf/ionic2-components#15]
Hi, i was looking for some sidemenu styled for ios and android, can you add it as an example on your app?

Will appreciate it so much :)

Thank you so much

**Comment by yannbf** [comment]
Hey @Fdom92, no problem at all.
Take a look at [this branch I just pushed](https://github.com/yannbf/ionic2-components/tree/sidemenu).

It's a work in progress, but you can start to get a few ideas from there.

**Comment by yannbf** [comment]
I'll make a few other styles, but at the moment there are two new sidemenus:
- One with avatar
- Small one on the right side

Take a look:
![sidemenu](https://cloud.githubusercontent.com/assets/1671563/23507552/6575f606-ff2c-11e6-92ae-50e4e2d7f520.gif)

**Comment by Fdom92** [comment]
Looks awesome :open_mouth: Great job!! :clap:

**Comment by yannbf** [comment]
Added material design side menu too. I integrated everything on master, you should be able to get it from the latest commit: e1aca4f.

**Comment by Fdom92** [comment]
Thank you so much @yannbf 👍
