### ISSUE TITLE
about ionic build --prod error 

### ISSUE THREAD

**Issue by liangwenzhong** [yannbf/ionic2-components#19]
hello , have u ever exec :  ionic build --prod ?
it seem report an error ~

**Comment by yannbf** [comment]
Hey Wen, thanks for opening an issue here!
It would have been best if you have provided any info, like the build output. Anyhow, I inspected and got the error - there wasn't a module for one of the pages in the app. I tried now and it's working with build --prod.

c1d86c4 fixes this problem.
