### ISSUE TITLE
Ionic 2 runtime Permission

### ISSUE THREAD

**Issue by Rajendra03dec** [yannbf/ionic2-components#2]
Hi ,

Can you please share a sample code or link, showing Marshmallow runtime permission using ionic 2 framework in Hybrid app

**Comment by yannbf** [comment]
Hey @Rajendra03dec , I just added an example for you under `miscellaneous/runtime-persmissions`. I hope it helps you out!

**Comment by Rajendra03dec** [comment]
Hey Yannbf,

Thanks for your kind help.

I have used user code at miscellaneous/runtime-persmissions . When i run the code in android phone and clicks on READ/WRITE EXTERNAL button it is not prompting for the permission means there is no dialogs asking for the permission.

**Comment by yannbf** [comment]
No problem!

Could you tell me on which android version are you testing? My tests were
on Android 6.0.1

**Comment by Rajendra03dec** [comment]
Hi ,

I am using Nexus 5 with android version 6.0.1

**Comment by Rajendra03dec** [comment]
Please update

**Comment by yannbf** [comment]
@Rajendra03dec it appears it was just your project that wasn't set correctly.
