### ISSUE TITLE
Error on iOS build

### ISSUE THREAD

**Issue by licalac** [yannbf/ionic2-components#25]
Hi,

First I would like to say a big thanks for putting all together all these stuff, very good and useful work.

Then so exiting after downloading I tried to deploy it on my iPhone using Xcode.

Just run an "ionic platform add ios" command and open the project in xCode 8.3 (running on macOS sierra 10.12.3)

Build failed whit issue :

/Users/lionel/Desktop/Ionic Dev Local/ionic3-components-master/platforms/ios/Advanced Ionic2 Components/Images.xcassets: None of the input catalogs contained a matching app icon set named  "AppIcon".

After what I tried to build with "ionic build ios" before re-open it in Xcode and then I have the following error:

** BUILD FAILED **

The following build commands failed:
	CompileStoryboard __PROJECT_NAME__/CDVLaunchScreen.storyboard
	CompileXIB __PROJECT_NAME__/Classes/MainViewController.xib

(2 failures)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/lionel/Desktop/Ionic Dev Local/ionic3-components-master/platforms/ios/cordova/build-debug.xcconfig,-workspace,Advanced Ionic2 Components.xcworkspace,-scheme,Advanced Ionic2 Components,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/lionel/Desktop/Ionic Dev Local/ionic3-components-master/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/lionel/Desktop/Ionic Dev Local/ionic3-components-master/platforms/ios/build/sharedpch

Hope I gave you enough informations

Regards

**Comment by yannbf** [comment]
Hey @licalac , thanks for opening an issue! It's actually quite difficult for me to test stuff on iOS, which is why would could end up seeing a few bugs on iOS devices, unfortunately. This error may be due to the app icon or something like that, peharps running `ionic resources --icon` could solve it. Sometimes I got errors on xcode I could only solve directly on xcode. 

I'll dig further and see if I can find what caused that.

**Comment by MikeyBeLike** [comment]
@yannbf that solves it, for clarification CLI 3, the command is ionic cordova resources --icon

**Comment by licalac** [comment]
Hi !

Thanks a lot guys it works like a charm now I can deploy your app on both OS.

Regards
