### ISSUE TITLE
Masonary style cards

### ISSUE THREAD

**Issue by Purus** [yannbf/ionic2-components#27]
**I'm submitting a ...**  (check one with "x")

[ ] bug report
[x] feature request
[ ] support request

How about showcasing masonary style ionic cards which adjust themselves during screen size change. Usage of Grid provides less flexibility.

**Comment by yannbf** [comment]
Hey @Purus I'm sorry for the late reply.

I added an example of that on 114ef19c5cd4ef3d. Let me know if it helps you!
