### ISSUE TITLE
errors when run ionic serve

### ISSUE THREAD

**Issue by adirzoari** [yannbf/ionic2-components#29]
**I'm submitting a ...**  (check one with "x")

[x ] bug report
[ ] feature request
[ ] support request

hello,
I upgraded to ionic 3.2.1 and when i run your app, I run before npm install and then ionic serve and I get errors
![image](https://cloud.githubusercontent.com/assets/20258998/26049064/54602cc2-3962-11e7-98f0-af7de3556e00.png)

**Comment by yannbf** [comment]
Hey @adirzoari I'm sorry for the late reply. I have updated the repository and it should be fixed. Give it a try and reopen the issue in case it didn't work for you.
