### ISSUE TITLE
Lazy load and routes

### ISSUE THREAD

**Issue by albertvp** [yannbf/ionic2-components#32]
**I'm submitting a ...** 

[ ] bug report
[x] feature request
[ ] support request

**Steps to reproduce the bug:**
I'm wondering if using lazy loaded component and pages might help performance on start.
For web browsers it's interesting to have also hash routes to go through a determined state or route.
There are some examples about this: https://ionicacademy.com/ionic-3-lazy-loading

**Related code:**
```typescript
tab1 = MyClientsPage; // from import

// can be
tab1:string = 'MyClientsPage';
```

**Comment by yannbf** [comment]
Hey Albert!

Thankfully, I just added lazyload to all pages, all you need to do is
update your local repo.

Let me know if it works for you.

Cheers!

Em 5 de jun de 2017 5:01 AM, "Albert Vilà Picas" <notifications@github.com>
escreveu:
