### ISSUE TITLE
Right side menu not displaying properly when screen in landscape view

### ISSUE THREAD

**Issue by venkatesh-nagineni** [yannbf/ionic2-components#34]
[ ] bug report
[x ] feature request
[ ] support request

When screen turns landscape view right side menu not displaying proper way here is screenshot how it looks like.
![screenshot_20170618-225537](https://user-images.githubusercontent.com/21661817/27264225-51937c50-547a-11e7-95ca-d9a27aaf14c7.png)

**Comment by yannbf** [comment]
Hey @venkatesh-nagineni, thanks for opening an issue! I just pushed a small change, hope it fixes your issue. Let me know if it didn't work for you!

**Comment by venkatesh-nagineni** [comment]
This works fine but there is some white strip adjacent to the icon menu. this is only in landscape view.
![27264225-51937c50-547a-11e7-95ca-d9a27aaf14c7](https://user-images.githubusercontent.com/21661817/27423329-8aaa347a-5731-11e7-846a-17387e0b0306.png)
