### ISSUE TITLE
tree component

### ISSUE THREAD

**Issue by plmercereau** [yannbf/ionic2-components#36]
**I'm submitting a tree component** 

[ ] bug report
[x] feature request
[ ] support request

Hello Yann,
Awesome repository, many thanks for sharing this! Have you thought about adding/developing an ionic tree component, in a kind of similar way as this [Angular Tree Component](https://github.com/500tech/angular-tree-component) ? It would be very helpful I guess!
Cheers
Pierre

**Comment by yannbf** [comment]
Hey @plmercereau !

Thanks a lot for opening an issue :))

Do you have any practical example of cases where this would be handy?
It is a bit of a complex component so I'd have to tweak a lot with it. I'll take a look and let you know! Seems like a nice idea!

**Comment by plmercereau** [comment]
Hello Yann!
Thanks for your reply! I was thinking about something similar to [Angular Tree](https://angular2-tree.readme.io/docs), but adapted to Ionic. I have to admit that my poor skills doesn't allow me to contribute in the adaptation myself! But if you believe this should be part of your since library, then it would be awesome! For instance to embed to menus, or to link to a "move" button that would open a modal with the tree to select the destination where you move your object... As an example to move files, emails, etc in a specific directory. My specific use case that I have in mind is to move an organisation unit in a tree of org units in the platform called [DHIS2](http://www.dhis2.org), in the same way you move a file/folder in Google Drive for instance.
Have a nice day!
Pierre

**Comment by corysmc** [comment]
I don't believe an organization tree is an appropriate pattern for mobile. Consult material design, see how google drive moves files/folders, or even how Dropbox does it. I'll upload an example soon: it'll be a modal that has its own navigation control. 

Cory McArthur

**Comment by corysmc** [comment]
See this example in my pull request: https://github.com/yannbf/ionic3-components/pull/39

**Comment by plmercereau** [comment]
Hello Cory, 
Your example seems pretty nice! The google drive / dropbox way to do is indeed more appropriate for mobile - it will be very helpful.
By the way @yannbf congrats for your Ionic hackathon prize - your may the 4th app is very inspiring.

**Comment by yannbf** [comment]
Hey @plmercereau, thank you!! The app served its purpose then :)

So, as @corysmc mentioned, he created an amazing example which is already integrated at master. Take a look at the "Modal with Navigation" section under the side menu!
