### ISSUE TITLE
ModalController cssClass option

### ISSUE THREAD

**Issue by kumarashu123** [yannbf/ionic2-components#37]
How to dynamically pass cssClass in ModalController.
As per document 
let profileModal = this.modalCtrl.create(Profile, { userId: 8675309 }, {cssClass: 'classname'});

But getting error - cssClass does not exist in the type model options.
May i know how to use dynamically cssClass while creating ModalController .

**Comment by yannbf** [comment]
Hey @kumarashu123 !

In this project there's a code which uses the same thing:
`this.modalCtrl.create('WalkthroughModalPage', null, { cssClass: 'inset-modal'});`

You can take a look at:
https://github.com/yannbf/ionic3-components/blob/master/src/pages/popup-modal/popup-modal.ts#L20

Try and check your ionic version, perhaps it has something to do with it.
