### ISSUE TITLE
modal with navigation

### ISSUE THREAD

**Issue by guizmo** [yannbf/ionic2-components#41]
Hi there,
i am trying to use your modalNav page which works half way> 
When i push a page the old one get destroyed in the stack so the back button functionality is broken

log error is :  Uncaught (in promise): navigation stack needs at least one root page

Appart from ModalWithNavigationPage, ModalNavPage and MoveDocumentPage, is there any thing i have missed ?

**Comment by guizmo** [comment]
Well nevermind...
I had my click event to push the new page in on a button, inside a form (calling the submit function).
That function had this.viewCtrl.dismiss({data}) in it... :/

Thanks for this repo ! it is extremely helpful

**Comment by yannbf** [comment]
Glad you got it solved! Thanks a lot for using the repo :)
