### ISSUE TITLE
Feature: Accordion

### ISSUE THREAD

**Issue by niconaso** [yannbf/ionic2-components#43]
**I'm submitting a ...**  (check one with "x")

[ ] bug report
[X] feature request
[ ] support request

It would be great if you include an accordion list component 😃

**Comment by yannbf** [comment]
Hey Nicolas, thanks a lot for opening an issue here! That's a great idea!
As soon as it's done, I'll let you know :+1:

**Comment by yannbf** [comment]
@niconaso Take a look at latest master or just commit b3a69e49403561b, I have pushed a suggestion. It was a bit tricky to make the animations, but I liked it at the end. Please let me know what you think!

**Comment by niconaso** [comment]
@yannbf thank you very much!! :smiley:

**Comment by yannbf** [comment]
@niconaso you're welcome! I tried to make it quite easy to customize it. If you have any requests on that, let me know :)
