### ISSUE TITLE
Your download should include empty www folder, so cordova prepare doesn't get confused!

### ISSUE THREAD

**Issue by jgfet** [yannbf/ionic2-components#44]
**I'm submitting a ...**  (check one with "x")

[ x] bug report
[ ] feature request
[ ] support request

**Steps to reproduce the bug:**
ran steps up to 
cordova prepare
Then I get
Error: Current working directory is not a Cordova-based project.

Fix is to have an empty www folder in git clone
See this related issue: https://github.com/ionic-team/ionic-cli/issues/935
**Related code:**
```
    insert any relevant code here
```

**Important information:**

**Comment by lohanidamodar** [comment]
I think with newer versions of CLI (3.1.0 and above) this problem does not exist.

**Comment by yannbf** [comment]
Thank you for opening this issue! I updated the installation flow in the docs, it's better to add a platform instead, which will update the plugins listed in config.xml.

Closing this issue for now!
