### ISSUE TITLE
how can I use my ionic as a online project，www？ 

### ISSUE THREAD

**Issue by JiaXinYi** [yannbf/ionic2-components#48]
help please~

**Comment by JiaXinYi** [comment]
very slow，not fast as your project like https://ioniccomponents.yannbraga.com

**Comment by xmano** [comment]
@JiaXinYi  Did you try with build "--prod" option?

**Comment by JiaXinYi** [comment]
@xmano ,yes. I tried, and my "www" file is 3.14M ,does it big?
,is there any reason else can make my site load so slow?

**Comment by yannbf** [comment]
@JiaXinYi the version I deployed in ioniccomponents.yannbraga.com is the same as master. I deployed using `npm run ionic:build --prod` then used my www folder.

**Comment by JiaXinYi** [comment]
@yannbf ，
I use ionic build --prod ,and my www file is here:
https://github.com/JiaXinYi/blog/tree/master/course
this is my site online: https://jiaxinyi.github.io/blog/course
load very slow at first time  ,It may take half a minute，Can you help me find out what went wrong?
Thank you for your  reply and waiting~

**Comment by yannbf** [comment]
Are you sure it isnt your Internet connection? It took half a second to
load the app in my phone

Em 18 de set de 2017 12:20 AM, "JiaXin" <notifications@github.com> escreveu:

**Comment by JiaXinYi** [comment]
@yannbf ,sincere thank you again , it‘s may because of the problem with my server & Internet,in fact ,I'm not sure still ,the time I spend on opening my website in my phone is not stable，if it's the first time I open an Ionic project ,it's slow ,at second time ,it's fast ,is that because of the cache problem ?

**Comment by yannbf** [comment]
I'm going to close this issue as it seems it doesn't have much to do with the repo. In case there's anything else, please create another issue and we can work on that.

Thanks!
