### ISSUE TITLE
how to define the root url?

### ISSUE THREAD

**Issue by MicroLord** [yannbf/ionic2-components#49]
eg:  #/nav/n4/miscellaneous
the url "/nav/n4" ,i don't see where does it config ?

**Comment by yannbf** [comment]
Hey @MicroLord this seemed to be an issue as of Ionic Angular 3.5. Did you upgrade to Ionic 3.6.1?
You can see a discussion about it here: https://github.com/ionic-team/ionic/issues/12346

**Comment by MicroLord** [comment]
Thank u , yesterday i upgrade the angular , ionic does not , still 3.10.3
