### ISSUE TITLE
Input type (instagram-login) Float Screen when OnFocus

### ISSUE THREAD

**Issue by cakrads** [yannbf/ionic2-components#50]
**I'm trying instagram-login**

When I try in my android, and I focus to type username..
The screen go up like this pict
[https://forum.ionicframework.com/uploads/default/original/3X/7/d/7d59faf5622c48031d7286b84abbbdb4744dda10.png](url)
how can i solve that.
that's ionic problem??
Or something. Ty

**Comment by yannbf** [comment]
Thanks for opening an issue. Due to this issue being very outdated and the image not available anymore, I will be closing this thread. Feel free to reopen the issue in case you still need support!
