### ISSUE TITLE
demo does't work

### ISSUE THREAD

**Issue by norahalkhunifer** [yannbf/ionic2-components#54]
**I'm submitting a ...**  (check one with "x")

[ ] bug report
[ ] feature request
[ ] support request

**Steps to reproduce the bug:**

**Related code:**
```
    insert any relevant code here
```

**Important information:**

**Comment by yannbf** [comment]
Hey all, thanks a lot for registering this issue. I was using a hosting provider that wasn't cool at all, and by having a high amount of requests it was being shut down automatically. I updated the repo to use github pages instead (updated README also), so this should not happen again.

You can access here: https://yannbf.github.io/ionic3-components

Thanks once again!
