### ISSUE TITLE
'npm install' is stuck not finishing

### ISSUE THREAD

**Issue by gokultrivandrum** [yannbf/ionic2-components#55]
After cloning latest commit , npm install is not finishing , It got stucked.

**Comment by yannbf** [comment]
Hey! So sorry to hear that. I'll take a look at it and solve it as soon as
I can. Thanks for reporting!

Em 12 de nov de 2017 12:11 AM, "gokultrivandrum" <notifications@github.com>
escreveu:

**Comment by gokultrivandrum** [comment]
Thanks for the quick reply, After a long time it got finished may be some repository down issue. Any way, ionic serve got success but "ionic cordova platform add android --device --prod" getting error like 

"Error parsing /home/gokul/Desktop/projects/ionic3-components/plugins/cordova-plugin-camera/plugin.xml.
Error: Unexpected end
Line: 0
Column: 0
Char: 
    at error (/home/gokul/.nvm/v7.10.0/lib/node_modules/cordova/node_modules/sax/lib/sax.js:347:8)
"

Do I need to add each ionic plugin one by one?

**Comment by yannbf** [comment]
That's not necessary. When adding a platform, cordova install each and every plugin for you. As this repository is huge because it has many different examples, it may take long, and also perhaps give an error like you had before. I'll try to reproduce your error and will soon let you know!

**Comment by gokultrivandrum** [comment]
Ok, 
I have copied the plugins from node_modules into plugins folder. But now ionic build android is getting error like this

Error: Type TimelineComponent in /ionic3-components/src/components/timeline/timeline.ts is part of the declarations of 2 modules: ComponentsModule in /ionic3-components/src/components/components.module.ts and TimelineComponentModule in /ionic3-components/src/components/timeline/timeline.module.ts! Please consider moving TimelineComponent in /ionic3-components/src/components/timeline/timeline.ts to a higher module that imports ComponentsModule in /ionic3-components/src/components/components.module.ts and TimelineComponentModule in /ionic3-components/src/components/timeline/timeline.module.ts. You can also create a new NgModule that exports and includes TimelineComponent in /ionic3-components/src/components/timeline/timeline.ts then import that NgModule in ComponentsModule in ionic3-components/src/components/components.module.ts and TimelineComponentModule in /ionic3-components/src/components/timeline/timeline.module.ts.

**Comment by gokultrivandrum** [comment]
Issue resolved by commenting the TimelineComponentModule, then run the ionic build. Successfully installed app.

**Comment by yannbf** [comment]
@gokultrivandrum I've solved this issue and many others (that happened after updating to Angular5), this should not happen anymore.

Thanks for opening this issue!
