### ISSUE TITLE
I get a error, when i build the project use command : npm run ionic:build --prod

### ISSUE THREAD

**Issue by linchanglin** [yannbf/ionic2-components#60]
I get a error, when i want to build the project use command : npm run ionic:build --prod
i use : npm 4.6.1; node 8.6.0, i did nothing after git clone .
![97157946-d62f-4d3e-934a-6bf466eb77f3](https://user-images.githubusercontent.com/16588715/32954106-1fdcf4d0-cbed-11e7-9bd8-c2fe63572bd0.png)

![5b70e34c-79f4-4187-9ecc-454dd1770f22](https://user-images.githubusercontent.com/16588715/32954138-39487d22-cbed-11e7-96f9-ec7d95121a54.png)

please help me , it has speed me three days . and used any methods i can find.

**Comment by yannbf** [comment]
@linchanglin thanks a lot for pointing this out!
It seems it's an issue regarding the new angular version, as this project was just updated to use angular 5.
This seems to be related: https://github.com/ionic-team/ionic-app-scripts/issues/1309

I'll take a further look later on, but if you downgrade to ionic 3.7 (or just angular to 4.4) I believe it will work without issues.
Please let me know if you move on with a solution for this also.

Thanks!

**Comment by linchanglin** [comment]
@yannbf thanks a lot for helping me.
as you said, it is seems to be the problem of "@ionic/app-scripts",  I figured out by downgrading angular to 4.1.3 and "@ionic/app-scripts": "^2.1.4", and it works fine.
Thanks again for your help！

**Comment by yannbf** [comment]
@linchanglin I have effectively fixed all issues regarding the newest Angular, so you can use the current version without any issues.
