### ISSUE TITLE
Side menu Integration

### ISSUE THREAD

**Issue by vishal2develop** [yannbf/ionic2-components#66]
I am trying to use the Avatar side menu for my app, but I cant integrate it into my app. What all code and files are needed to be copied? 
Could anyone help me out with it please as I need it for my project asap? 
Thank you.

P.S: I'm a newbie to ionic

**Comment by yannbf** [comment]
Hey @vishal2develop, thanks for your interest in this repository!
You have to get the HTML code from app.html regarding your desired sidemenu, then its css from app.scss. This shows to me that I have to add a README explaining how to do so for new users. Thanks for your feedback :)

Here's the gist with what you have to use: https://gist.github.com/yannbf/0f2fea2421dee8e388b4d0c5e78ba480

Just change the logic and assets.

**Comment by vishal2develop** [comment]
Thank you so much for your valuable and prompt reply. Will copying the **app.html and app.scss** replace the default style of the menu. 
I don't want to click on a button to change the  UI of the side menu. I want the **avatar mode to be my default.**
How am I supposed to do that?

**Comment by yannbf** [comment]
yes, if you integrate that code with yours, the avatar sidemenu will be displayed by default.

**Comment by yannbf** [comment]
I'm gonna close this issue as it seems to be resolved. I provided you all the ingredients, so you just need to bake the cake.

Thanks!
