### ISSUE TITLE
Demo site currently unavailable

### ISSUE THREAD

**Issue by jjjhanreyyy** [yannbf/ionic2-components#67]
**I'm submitting a ...**  (check one with "x")

[x ] bug report
[ ] feature request
[ ] support request

**Steps to reproduce the bug:**
Visit https://ioniccomponents.yannbraga.com/

**Important information:**

I am trying to visit the demo first. But the site is down. Seems problem with hosting.

**Comment by yannbf** [comment]
Hey @jjjhanreyyy, thanks a lot for registering this issue. I was using a hosting provider that wasn't cool at all, and by having a high amount of requests it was being shut down automatically. I updated the repo to use github pages instead (updated README also), so this should not happen again.

You can access here: https://yannbf.github.io/ionic3-components

Thanks once again!
