### ISSUE TITLE
code ionic view not working

### ISSUE THREAD

**Issue by juanurcola** [yannbf/ionic2-components#77]
Hi !
The project in the repository of ionic view , is public ? 
Because i cant download with this code bd1b6d71.
Thnks

**Comment by deriegle** [comment]
I just tried it and received a message saying there were no public channels for this app.

**Comment by imVinayPandya** [comment]
I am having the same problem

**Comment by yannbf** [comment]
Thanks for opening this issue. Ionic View has been shut down, for that reason I will be closing it.
