### ISSUE TITLE
Online example out of sync with repo

### ISSUE THREAD

**Issue by ShadowMitia** [yannbf/ionic2-components#98]
**I'm submitting a ...**  (check one with "x")

[X] bug report
[ ] feature request
[ ] support request

The online example here: https://yannbf.github.io/ionic3-components isn't in sync with the code on master branch. On the homepage you can see referenes to Ionic2 while this repo is all about Ionic3.

**Related code:**
```
```

**Important information:**

**Comment by anuj9196** [comment]
I am also facing this issue. Example layout is different from the repo.

**Comment by yannbf** [comment]
Thanks for opening the issue! The application has been updated.
